# Generated by Django 3.1.2 on 2020-11-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.BigIntegerField(blank=True, null=True)),
                ('connection_id', models.BigIntegerField(blank=True, null=True)),
                ('function_name', models.TextField(blank=True, null=True)),
                ('source_connection_name', models.TextField(blank=True, null=True)),
                ('is_fixed_width', models.BooleanField(blank=True, null=True)),
                ('field_name', models.TextField(blank=True, null=True)),
                ('parameter_data_type', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(blank=True, null=True)),
                ('parameter_default_value', models.TextField(blank=True, null=True)),
                ('help', models.TextField(blank=True, null=True)),
                ('return_type', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'connection_parameters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('connection_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('connection_name', models.TextField(blank=True, null=True)),
                ('connection_type_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'connections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type_id', models.IntegerField()),
                ('connection_type', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'connection_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseSources',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'database_sources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataInstance',
            fields=[
                ('data_instance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('unificater_flow_id', models.IntegerField()),
                ('data_instance_object_name', models.CharField(max_length=1000)),
                ('data_instance_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('query_text', models.TextField(blank=True, null=True)),
                ('data_instance_object_status', models.CharField(blank=True, max_length=100, null=True)),
                ('data_instance_error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_instance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('datasource_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datasource_name', models.TextField()),
                ('sqlview', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datasource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasourceConnections',
            fields=[
                ('connection_id', models.IntegerField(primary_key=True, serialize=False)),
                ('connection_name', models.CharField(max_length=250, unique=True)),
                ('connection_createddate', models.DateTimeField(blank=True, null=True)),
                ('sourceid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datasource_connections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstanceTbl',
            fields=[
                ('instance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('instance_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('used_in_flow', models.CharField(blank=True, max_length=20, null=True)),
                ('unificater_flow_id', models.IntegerField(blank=True, null=True)),
                ('connection_status', models.CharField(blank=True, max_length=1000, null=True)),
                ('instance_error_message', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'instance_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReqConnectionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('isrequired', models.CharField(blank=True, max_length=250, null=True)),
                ('server_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'req_connection_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnificaterFlows',
            fields=[
                ('unificater_flow_id', models.IntegerField(primary_key=True, serialize=False)),
                ('unificater_flow_name', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('unificater_flow_latest_version_id', models.IntegerField(blank=True, null=True)),
                ('sub_flows_exist', models.CharField(blank=True, max_length=100, null=True)),
                ('updatable', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'unificater_flows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserConnectionParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('user_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('unificater_flow_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_connection_parameters',
                'managed': False,
            },
        ),
    ]
