# Generated by Django 3.1.2 on 2020-11-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unificater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInstance1',
            fields=[
                ('data_instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_id', models.IntegerField(blank=True, null=True)),
                ('unificater_flow_id', models.IntegerField()),
                ('data_instance_object_name', models.CharField(max_length=1000)),
                ('connection_id', models.IntegerField(blank=True, null=True)),
                ('data_instance_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('query_text', models.TextField(blank=True, null=True)),
                ('data_instance_object_status', models.CharField(blank=True, max_length=100, null=True)),
                ('data_instance_error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_instance1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstanceTbl1',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('connection_id', models.IntegerField(blank=True, null=True)),
                ('used_in_flow', models.CharField(blank=True, max_length=20, null=True)),
                ('unificater_flow_id', models.IntegerField(blank=True, null=True)),
                ('connection_status', models.CharField(blank=True, max_length=1000, null=True)),
                ('instance_error_message', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'instance_tbl1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnificaterFlows1',
            fields=[
                ('unificater_flow_id', models.AutoField(primary_key=True, serialize=False)),
                ('unificater_flow_name', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('unificater_flow_latest_version_id', models.IntegerField(blank=True, null=True)),
                ('sub_flows_exist', models.CharField(blank=True, max_length=100, null=True)),
                ('updatable', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'unificater_flows1',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DataInstance',
        ),
        migrations.DeleteModel(
            name='InstanceTbl',
        ),
        migrations.DeleteModel(
            name='UnificaterFlows',
        ),
    ]
